name: Build Docker Image on Push to Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r dependencias.txt
          pip install pytest requests

      - name: Iniciar servidor en segundo plano
        run: |
          nohup python app.py &
          sleep 5

      - name: Ejecutar pruebas
        run: pytest tests/

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/predictor-enfermedades
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
